Repository sendgrid/smtpapi-php, pull requests merged in 2020-01, with the labels that each got.

#110 chore: prep the repo for automated releasing
  .gitignore
  .travis.yml
  CHANGELOG.md
  LICENSE.txt
  Makefile
  README.md
  composer.json
  composer.lock
  scripts/generate_upload_policy.php
  scripts/s3policy.json
  scripts/s3upload.sh
  smtpapi-php.php
  test/Dockerfile
  test/RepoFilesExistsTest.php
  test/Smtpapi.php
  test/Smtpapi/HeaderTest.php
  test/bootstrap.php
  test/phpunit.xml.dist
Labels: status: code review request

#82 docs: Add Code Reviews Section to README
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request

#109 docs: Add use cases directory
  use_cases/README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#77 docs: makes Environmental Variables a sub topic in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request

#76 chore: Add CodeCov support to .travis.yml
  .travis.yml
Labels: difficulty: easy, status: code review request

#84 docs: update old URL's with the latest ones
  examples/example.php
Labels: difficulty: easy, status: code review request

#111 docs: baseline all the templated markdown docs
  .github/ISSUE_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  test/RepoFilesExistsTest.php
  test/Smtpapi/HeaderTest.php
Labels: status: code review request
